name: cyrtranslit
description:  Transliterate Cyrillic script to Latin script and vice versa.
version: 1.0.1
repository: https://github.com/sun-jiao/cyrillic-transliteration

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
